### ISSUE TITLE
能否支持v2ray 规则文件?

### ISSUE THREAD

**Issue by lostz** [leiless/dnsredir#12]
能否支持v2ray 规则文件?geosite:geolocation-!cn,这样可以直接复用https://github.com/Loyalsoldier/v2ray-rules-dat,这类规则文件,谢谢.

**Comment by leiless** [comment]
你是指支持解析 [geosite.dat](https://github.com/Loyalsoldier/v2ray-rules-dat/releases) 这类文件吗？
这种情况下 `dnsredir FROM { TO... }` 你希望怎么写？抱歉我没怎么用过geosite。

**Comment by lostz** [comment]
dnsredir geosite:cn {}
这种写法

**Comment by leiless** [comment]
`FROM` 需要是一个文件路径，URL，或者是`.` (root zone)。
如果需要支持你上面的用法，需要借鉴类似URL锚点来实现这个功能。

例子：
```
dnsredir geosite.dat#geosite:cn {
    ...
}
```

这样似乎会让目前parse FROM的代码变得有点奇怪，可能暂时不会考虑这样做，希望保持代码的简单。
（当然，如果你有更好的处理你说到的问题的方法也可以提出来）

<br/>
<br/>

我注意到 https://github.com/Loyalsoldier/v2ray-rules-dat#geositedat 里面：
> @felixonmars/dnsmasq-china-list/accelerated-domains.china.conf 加入到 `geosite:cn` 类别中

如果你只需要使用`geosite:cn`的话，可以参考[这个链接](https://gist.github.com/leiless/5fbdeafb69d56fe737ba639ded9ac124#gistcomment-3259422)给出的`Corefile`例子：
```
# accelerated, apple, google
dnsredir https://t.cn/A6zY4e4i https://t.cn/A6zYb6sL https://t.cn/A6zYbWEM {
    ...
}
```

使用URL的方式直接获取，本质上都是从 `felixonmars/dnsmasq-china-list` 获取的列表。

**Comment by lostz** [comment]
了解,谢谢.
