### ISSUE TITLE
时常出现“write broken",这是什么原因？

### ISSUE THREAD

**Issue by cnclg** [leiless/dnsredir#17]
root@Wireguard:/etc/coredns# tail -f /var/log/syslog 
Aug 30 18:10:02 Wireguard coredns[16605]: [WARNING] plugin/dnsredir: Exchange() failed  error: write tcp 10.10.100.3:25908->1.1.1.1:853: write: broken pipe
Aug 30 18:11:15 Wireguard coredns[16605]: [WARNING] plugin/dnsredir: tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 10.10.100.3:26130->1.1.1.1:853: write: broken pipe
Aug 30 18:11:15 Wireguard coredns[16605]: [WARNING] plugin/dnsredir: Exchange() failed  error: write tcp 10.10.100.3:26130->1.1.1.1:853: write: broken pipe
Aug 30 18:11:15 Wireguard coredns[16605]: [WARNING] plugin/dnsredir: tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 10.10.100.3:26128->1.1.1.1:853: write: broken pipe
Aug 30 18:11:15 Wireguard coredns[16605]: [WARNING] plugin/dnsredir: Exchange() failed  error: write tcp 10.10.100.3:26128->1.1.1.1:853: write: broken pipe
Aug 30 18:11:51 Wireguard coredns[16605]: [WARNING] plugin/dnsredir: tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 10.10.100.3:26196->1.1.1.1:853: write: broken pipe
Aug 30 18:11:51 Wireguard coredns[16605]: [WARNING] plugin/dnsredir: Exchange() failed  error: write tcp 10.10.100.3:26196->1.1.1.1:853: write: broken pipe
Aug 30 18:13:21 Wireguard coredns[16605]: [WARNING] plugin/dnsredir: tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 10.10.100.3:26340->1.1.1.1:853: write: broken pipe
Aug 30 18:13:21 Wireguard coredns[16605]: [WARNING] plugin/dnsredir: tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 10.10.100.3:26350->1.1.1.1:853: write: broken pipe

**Comment by leiless** [comment]
`10.10.100.3:... -> 1.1.1.1:853: write: broken pipe`

你使用的是Cloudflare 1.1.1.1 DoT，大概率是因为你的ISP上游断流导致的，`dnsredir` 会复用已经打开的TLS连接，所以出现如下情况时会出现 `write: broken pipe`：
* 用户请求DNS，一个TLS被成功建立。
* 响应完用户DNS，连接没有被立刻关闭（KeepAlive）。
* 过了一会儿，上游ISP将你本地的链接强制断开。
* 与此同时，一个新的用户DNS请求到来，复用之前建立的连接。
* 写DNS message写入到该TLS链接时候报错：`write: broken pipe`。

这个问题我也遇到过，发现宽带运营商会针对一些常见的DoT/DoH产生断流现象。

SEE ALSO:
https://gist.github.com/leiless/5fbdeafb69d56fe737ba639ded9ac124#gistcomment-3654247

**Comment by cnclg** [comment]
谢谢，换了doh基本没在出现类似错误。
