### ISSUE TITLE
dnsredir pf.AddIP(): cannot add 

### ISSUE THREAD

**Issue by chencxin** [leiless/dnsredir#24]
![image](https://user-images.githubusercontent.com/40486630/143539001-9ebe2341-1127-492c-b143-067f74da5519.png)

The problem is shown above

environment：MACOS 10.15.7
config:
    dnsredir . {
        expire 15s
        max_fails 3
        health_check 3s
        policy round_robin
        path_reload 2s
        to 114.114.114.114 223.5.5.5 119.29.29.29
        pf aa +v4_only
    }

question:
            Is there a problem with the pf configuration？
           Can you give a demo of pf configuration?

**Comment by leiless** [comment]
> Is there a problem with the pf configuration？

Yes

The manual is at https://github.com/leiless/dnsredir#syntax

```
pf +create +v4_only aa # Create table aa if not exists, add IPv4 only
```

Note that the options must come before the pf table name: `pf [+OPTION...] NAME[:ANCHOR]...`

**Comment by chencxin** [comment]
OK, thanks

**Comment by leiless** [comment]
Close, any update please reopen or open a new issue.

**Comment by chencxin** [comment]
Already resolved
