### ISSUE TITLE
不支持v6 doh

### ISSUE THREAD

**Issue by hingbong** [leiless/dnsredir#26]
`[WARNING] plugin/dnsredir: hc: DNS https://2001:4860:4860::64 failed  rtt: 0s err: Get "https://2001:4860:4860::64?ct=application/dns-message&dns=AAABAAABAAAAAAAAAAACAAE": dial tcp: lookup 2001:4860:4860:: no such host`使用`to doh://2001:4860:4860::64@dns.google`时出现

**Comment by leiless** [comment]
Hi, thanks for reporting.
Can you manually verify the output of `curl -4IL https://ipv6.icanhazip.com` before I investigate this?

**Comment by leiless** [comment]
I can confirm this bug by the following config:

```Corefile
.:10053 {
    hosts {
        fallthrough
    }

    # see:
    #   https://github.com/curl/curl/wiki/DNS-over-HTTPS
    #   https://kb.adguard.com/en/general/dns-providers#adguard-dns
    dnsredir . {
        expire 30s
        max_fails 5
        health_check 10s
        policy random
        spray

        to doh://2001:4860:4860::8844@dns.google
    }
}
```

```
curl -svL 'https://[2001:4860:4860::8888]/resolve?ct=application/dns-json&name=227682103694361404.1739265051992080517.&type=HINFO' | jq
```

The reason is that the IPv6 address should be double-quoted when combined with port (used in config parse and DoH exchange)
I'll fix this later.
