### ISSUE TITLE
API modifed in latest CoreDNS

### ISSUE THREAD

**Issue by missdeer** [leiless/dnsredir#5]
Build failed at  https://github.com/leiless/dnsredir/blob/2b46fc33a2016d8c8d4eaf1f3a00f80cc970dd34/setup.go#L27-L34 with the latest CoreDNS

**Comment by leiless** [comment]
Thanks for your feedback, it seems the function signature changed, I'll check it later..

**Comment by leiless** [comment]
Done with https://github.com/leiless/dnsredir/commit/0f45c04ae452c2b3a34b481339bb4645334b6151
Taken form https://github.com/coredns/coredns/commit/4166dcc2feab0b42b6e7748a6078d0f5d3d54186
