### ISSUE TITLE
CoreDNS is using internal caddy package now

### ISSUE THREAD

**Issue by missdeer** [leiless/dnsredir#6]
https://github.com/coredns/coredns/commit/b003d06003750e26d1621c1d6167ce63ecd824d5

**Comment by leiless** [comment]
Thanks for your feedback, @missdeer, I'll check that later.

**Comment by leiless** [comment]
Commit https://github.com/coredns/coredns/commit/b003d06003750e26d1621c1d6167ce63ecd824d5 will be released under 1.8.0(see [history](https://github.com/coredns/coredns/commits/master)), currently dnsredir will build upon latest release(not the latest commit), thus we'll wait for several days so the CI can be proceeded.

**Comment by leiless** [comment]
CoreDNS 1.8.0 is released, now the CI can proceed.
https://cloud.drone.io/leiless/dnsredir/147

Close this.
