### ISSUE TITLE
build failed on macOS

### ISSUE THREAD

**Issue by missdeer** [leiless/dnsredir#7]
```txt
../dnsredir/pf_darwin.go:96:17: undefined: pf.Open
../dnsredir/pf_darwin.go:100:23: undefined: pf.IsEnabled
../dnsredir/pf_darwin.go:113:23: undefined: pf.AddTable
../dnsredir/pf_darwin.go:128:9: undefined: pf.Close
../dnsredir/pf_darwin.go:163:21: undefined: pf.AddAddr
```
more details on https://ci.appveyor.com/project/missdeer/coredns-custom-build/build/job/f957327phk5cr7ko

seems that **dnsredir** depends on **cgo** so that it can't be cross-built, right?

**Comment by leiless** [comment]
> seems that dnsredir depends on cgo so that it can't be cross-built, right?

Sorry for the inconvenience. By now, yes, **dnsredir** now can add IP addresses to pf table, which utilized CGo to achieve this goal.

Currently, I use macOS to compile **dnsredir** for darwin.
https://github.com/leiless/dnsredir/blob/master/.github/workflows/staging.yml#L159

It seems that the darwin pf part can be replaced by golang's builtin [syscall](https://golang.org/pkg/syscall/) package(Haven't check it yet)
If it's possible, the CGo part can be dropped eventually.

**Comment by missdeer** [comment]
Thanks, it works.
https://ci.appveyor.com/project/missdeer/coredns-custom-build/build/job/hqf1puaha559mdyw
